[package]
name = "cxedit"
version = "0.1.0"
authors = ["Simon Farre <simon.farre.cx@gmail.com>"]
edition = "2018"

[dependencies]
libc = "*"
termios = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
dbus = "*"
